{
 "title": "Block Stats",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Base Fee (% of Minimum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vechain_base_fee\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vechain_tps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")"
    }
   ]
  },
  {
   "title": "Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vechain_gas_used\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> map(fn: (r) => ({ r with _value: (r._value / 40000000.0) * 100.0 }))"
    }
   ]
  }
 ]
}