{
 "title": "Influx DB v2 Stats",
 "time": { "from": "now-1m", "to": "now+4m" },
 "templating": {
  "list": [
   {
    "name": "http_metric",
    "label": "HTTP",
    "query": "http_req_blocked,http_req_connecting,http_req_duration,http_req_failed,http_req_receiving,http_req_sending,http_req_tls_handshaking,http_req_waiting"
   },
   {
    "name": "test_name",
    "label": "Test",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"vechain\", tag: \"test_name\")\n"
    }
   },
   {
    "name": "test_run_id",
    "label": "ID",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"vechain\", tag: \"test_run_id\")\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Test Colours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Requests Made",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "import \"array\"\nimport \"strings\"\nimport \"influxdata/influxdb/schema\"\n\ntest_run_first_entries = from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> first() // Get the first entry per test_run_id\n  |> keep(columns: [\"_time\", \"test_run_id\"])\n\ncurrentTime = now()\n\ntest_map = test_run_first_entries\n  |> reduce(\n    fn: (r, accumulator) => ({\n        test_run_id: r[\"test_run_id\"],\n        first_time: if accumulator.first_time == time(v: 0) then r._time else accumulator.first_time\n    }),\n    identity: {test_run_id: \"\", first_time: time(v: 0)}\n  )\n  |> map(fn: (r) => ({\n      test_run_id: r.test_run_id,\n      shift: uint(v: currentTime) - uint(v: r.first_time) // Convert _time to uint here\n  }))\n\ndata = from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> aggregateWindow(every: 1s, fn: sum, createEmpty: false)\n\n\njoined = join(tables: {data: data, shifts: test_map}, on: [\"test_run_id\"])\n\nresult = joined\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      test_run_id: r.test_run_id,\n      shift: r.shift\n    }))\n  |> map(fn: (r) => ({\n      _time: time(v: uint(v: r._time) + r.shift),\n      _value: r._value,\n      test_run_id: r.test_run_id\n    }))\n\nresult |> yield(name: \"_value\")\n"
    }
   ]
  },
  {
   "title": "P(90)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r._measurement == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> quantile(q: 0.90, method: \"exact_mean\")"
    }
   ]
  },
  {
   "title": "P(99)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r._measurement == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> quantile(q: 0.99, method: \"exact_mean\")"
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "query": "import \"array\"\nimport \"strings\"\nimport \"influxdata/influxdb/schema\"\n\ncurrentTime = now()\n\ntest_run_first_entries = from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> first() // Get the first entry per test_run_id\n  |> keep(columns: [\"_time\", \"test_run_id\"])\n\ntest_map = test_run_first_entries\n  |> reduce(\n    fn: (r, accumulator) => ({\n        test_run_id: r[\"test_run_id\"],\n        first_time: if accumulator.first_time == time(v: 0) then r._time else accumulator.first_time\n    }),\n    identity: {test_run_id: \"\", first_time: time(v: 0)}\n  )\n  |> map(fn: (r) => ({\n      test_run_id: r.test_run_id,\n      shift: uint(v: currentTime) - uint(v: r.first_time) // Convert _time to uint here\n  }))\n\ndata = from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vus\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\n\njoined = join(tables: {data: data, shifts: test_map}, on: [\"test_run_id\"])\n\nresult = joined\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      test_run_id: r.test_run_id,\n      shift: r.shift\n    }))\n  |> map(fn: (r) => ({\n      _time: time(v: uint(v: r._time) + r.shift),\n      _value: r._value,\n      test_run_id: r.test_run_id\n    }))\n\nresult |> yield(name: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Mean",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r._measurement == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> mean()"
    }
   ]
  },
  {
   "title": "Mean over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 16 },
   "targets": [
    {
     "query": "import \"array\"\nimport \"strings\"\nimport \"influxdata/influxdb/schema\"\n\ncurrentTime = now()\n\nhttp_metric=\"http_req_duration\"\n\ntest_run_first_entries = from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> first() \n  |> keep(columns: [\"_time\", \"test_run_id\"])\n\n\ntest_map = test_run_first_entries\n  |> reduce(\n    fn: (r, accumulator) => ({\n        test_run_id: r[\"test_run_id\"],\n        first_time: if accumulator.first_time == time(v: 0) then r._time else accumulator.first_time\n    }),\n    identity: {test_run_id: \"\", first_time: time(v: 0)}\n  )\n  |> map(fn: (r) => ({\n      test_run_id: r.test_run_id,\n      shift: uint(v: currentTime) - uint(v: r.first_time) // Convert _time to uint here\n  }))\n\ndata = from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n\njoined = join(tables: {data: data, shifts: test_map}, on: [\"test_run_id\"])\n\nresult = joined\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      test_run_id: r.test_run_id,\n      shift: r.shift\n    }))\n  |> map(fn: (r) => ({\n      _time: time(v: uint(v: r._time) + r.shift),\n      _value: r._value,\n      test_run_id: r.test_run_id\n    }))\n\nresult |> yield(name: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Median",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r._measurement == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> quantile(q: 0.50, method: \"exact_mean\")"
    }
   ]
  },
  {
   "title": "Median over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 24 },
   "targets": [
    {
     "query": "import \"array\"\nimport \"strings\"\nimport \"influxdata/influxdb/schema\"\n\ncurrentTime = now()\n\nhttp_metric=\"http_req_duration\"\n\ntest_run_first_entries = from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> first() \n  |> keep(columns: [\"_time\", \"test_run_id\"])\n\n\ntest_map = test_run_first_entries\n  |> reduce(\n    fn: (r, accumulator) => ({\n        test_run_id: r[\"test_run_id\"],\n        first_time: if accumulator.first_time == time(v: 0) then r._time else accumulator.first_time\n    }),\n    identity: {test_run_id: \"\", first_time: time(v: 0)}\n  )\n  |> map(fn: (r) => ({\n      test_run_id: r.test_run_id,\n      shift: uint(v: currentTime) - uint(v: r.first_time) // Convert _time to uint here\n  }))\n\ndata = from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> aggregateWindow(every: 10s, fn: median, createEmpty: false)\n\njoined = join(tables: {data: data, shifts: test_map}, on: [\"test_run_id\"])\n\nresult = joined\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      test_run_id: r.test_run_id,\n      shift: r.shift\n    }))\n  |> map(fn: (r) => ({\n      _time: time(v: uint(v: r._time) + r.shift),\n      _value: r._value,\n      test_run_id: r.test_run_id\n    }))\n\nresult |> yield(name: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Max",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r._measurement == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> max()"
    }
   ]
  },
  {
   "title": "Max Values over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 32 },
   "targets": [
    {
     "query": "import \"array\"\nimport \"strings\"\nimport \"influxdata/influxdb/schema\"\n\ncurrentTime = now()\n\ntest_run_first_entries = from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> first() \n  |> keep(columns: [\"_time\", \"test_run_id\"])\n\n\ntest_map = test_run_first_entries\n  |> reduce(\n    fn: (r, accumulator) => ({\n        test_run_id: r[\"test_run_id\"],\n        first_time: if accumulator.first_time == time(v: 0) then r._time else accumulator.first_time\n    }),\n    identity: {test_run_id: \"\", first_time: time(v: 0)}\n  )\n  |> map(fn: (r) => ({\n      test_run_id: r.test_run_id,\n      shift: uint(v: currentTime) - uint(v: r.first_time) // Convert _time to uint here\n  }))\n\ndata = from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> aggregateWindow(every: 10s, fn: max, createEmpty: false)\n\n\njoined = join(tables: {data: data, shifts: test_map}, on: [\"test_run_id\"])\n\nresult = joined\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      test_run_id: r.test_run_id,\n      shift: r.shift\n    }))\n  |> map(fn: (r) => ({\n      _time: time(v: uint(v: r._time) + r.shift),\n      _value: r._value,\n      test_run_id: r.test_run_id\n    }))\n\nresult |> yield(name: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Min",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r._measurement == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> min()"
    }
   ]
  },
  {
   "title": "Min Values over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 40 },
   "targets": [
    {
     "query": "import \"array\"\nimport \"strings\"\nimport \"influxdata/influxdb/schema\"\n\ncurrentTime = now()\n\ntest_run_first_entries = from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> first() \n  |> keep(columns: [\"_time\", \"test_run_id\"])\n\n\ntest_map = test_run_first_entries\n  |> reduce(\n    fn: (r, accumulator) => ({\n        test_run_id: r[\"test_run_id\"],\n        first_time: if accumulator.first_time == time(v: 0) then r._time else accumulator.first_time\n    }),\n    identity: {test_run_id: \"\", first_time: time(v: 0)}\n  )\n  |> map(fn: (r) => ({\n      test_run_id: r.test_run_id,\n      shift: uint(v: currentTime) - uint(v: r.first_time) // Convert _time to uint here\n  }))\n\ndata = from(bucket: \"vechain\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${http_metric}\")\n  |> filter(fn: (r) => contains(value: r[\"test_run_id\"], set: ${test_run_id:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"test_run_id\", \"_measurement\"])\n  |> aggregateWindow(every: 10s, fn: min, createEmpty: false)\n\n\njoined = join(tables: {data: data, shifts: test_map}, on: [\"test_run_id\"])\n\nresult = joined\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      test_run_id: r.test_run_id,\n      shift: r.shift\n    }))\n  |> map(fn: (r) => ({\n      _time: time(v: uint(v: r._time) + r.shift),\n      _value: r._value,\n      test_run_id: r.test_run_id\n    }))\n\nresult |> yield(name: \"_value\")\n"
    }
   ]
  }
 ]
}